### ISSUE TITLE
Need to track deliveries of ingredients by vendors

### ISSUE THREAD

**Issue by ToddPeterson** [ToddPeterson/bobs_eatery#3]
Needed for delivery 4 - query 6.

**Comment by delaneyemoore** [comment]
Should we create a new table all together? That tracks the vendor, the date, and what ingredient was delivered?

**Comment by ToddPeterson** [comment]
I think that would be enough for what the delivery asks for. We could separate Deliveries from DeliveryItems, but that seems like overkill for our purposes.

**Comment by ToddPeterson** [comment]
Deliveries(DeliveryID, IngredientID, DateDelivered, VendorID)

**Comment by KingWASD** [comment]
I've added/updated those columns so they'll work with our queries. Changes are committed in the dev branch. Reopen the issue if something needs to be changed.
