### ISSUE TITLE
Create City Form

### ISSUE THREAD

**Issue by Sanvasbin** [ToddPeterson/bobs_eatery#35]
This Form will be embedded to create/edit Customer or Employee

**Comment by ToddPeterson** [comment]
No need for a separate form. Just replace the CityID field with City Name, State Name, and Zip Code. When creating/updating a customer/employee, call the create city sproc first to get the CityID, then use that CityID when you call the create/update customer/employee sproc.

**Comment by Sanvasbin** [comment]
There is a form too.
Also When u edit or create employees now, you can change the city, zip code, and state which will call create city sproc and it can add new or return city id to link back to the employee.
